name: Remote Dispatch Action Initiator
 
on:
  push:
  repository_dispatch:
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
          curl -X POST https://api.github.com/repos/shebangops/action-b/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{ secrets.ACCESS_TOKEN }}   --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          sleep 10
      - name: ACK - Acknowledge pong from remote repositoryy
        if: github.event.action == 'pong'
        run: |
          echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
          curl -X POST https://api.github.com/repos/shebangops/action-b/dispatches \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
